name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install OpenGL
      run: |
          sudo apt update
          sudo apt install -y xorg-dev libgl1-mesa-dev libxkbcommon-x11-dev libwayland-dev libx11-xcb-dev libvulkan-dev
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: Build
      run: go build -v ./...
    - name: Tests with coverage
      run: go test -race -v -count=1 -coverprofile=coverage.out ./...
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1
      with:
        name: codecov
        fail_ci_if_error: true
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: latest
